#!/bin/sh
set -e

case "$1" in
    configure)
        if ! getent passwd _acmers > /dev/null 2>&1; then
            adduser --system --no-create-home --group _acmers
        fi
        chown -R _acmers:_acmers /var/lib/acmers
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
