#!/bin/sh
set -e

case "$1" in
    purge)
        rm -rf /var/lib/acmers
        if getent passwd _acmers > /dev/null 2>&1; then
            deluser --system _acmers
        fi
    ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
